### ISSUE TITLE
About uvc patch

### ISSUE THREAD

**Issue by Wesley-Lin** [PercATI/RealSense_ROS#10]
Hi Amit,

As I know, the uvcdriver patch in  ds_uvcdriver folder is adding the format to meet the IR and depth raw data. After I apply the patch,  I try to use the VLC application to read the data from Depth image and IR image, but the IR and Depth streaming in VLC show  green color, is it normal ? what can I do to see the normal IR and Depth streaming ?
And other question is, if I want to use v4l2 to read the IR, depth and RGB data, May I just install the ds_uvcdriver instead of all the r200_driver ?

Many question need you confirm
Thanks a lot
Regards

**Comment by AmitMoran** [comment]
Hi,
I am not sure VLC should work out of the box.
You should use a dedicated viewer. In the ROS sample you can see one.

The uvc driver patch just adds the pixel set. You do want to have the API for all possible manipulation. 

Thanks,
Amit
