### ISSUE TITLE
Something wrong with realsenseRvizConfig.rviz

### ISSUE THREAD

**Issue by niezeroxue** [PercATI/RealSense_ROS#15]
Hi Amit, 
I have a trouble with realsenseRvizConfig.rviz. Firstly, I ran r200_install/install.sh under r200_install,and then excuted DSReadCameraInfo sucessfully. Then I open the folder realsense_dist, ran the install_realsense_ros.sh, after that I ran the nodelet in terminal by roslaunch realsense realsense_r200_launch.launch, the r200 camera lights up.Then I try to run the realsenseRvizConfig.rviz in rViz, I get an error, the error image is shown below:

![screenshot from 2015-11-20 18 37 24](https://cloud.githubusercontent.com/assets/6767575/11297799/c8397386-8fb5-11e5-8df7-9763fe9308db.png)

It shows that " Global Status Error---Fixed Frame--- Fixed Frame [world] does not exist". The rgb image and the depth image are right, but the point cloud view is wrong, it shows nothing.
So what wrong with the matter?
Best regards!

**Comment by PercATI** [comment]
It might be the case that the current published version is using realsense_frame as the base frame.

can you give it a try?

We will publish a version soon that you can choose the frames yourself.

thanks,
amit
