### ISSUE TITLE
There is nothing when I lunch Sample Image Viewer Nodelet

### ISSUE THREAD

**Issue by Wesley-Lin** [PercATI/RealSense_ROS#16]
Hi Amit,

I have a issue with realsense_image_viewer_launch.launch, and I had excuted DSReadCameraInfo sucessfully. Then I lunch realsense_r200_launch.launch, it would pop three windows. However, there are nothing in it.  Here is my snapshot for your reference
![view_is_empty](https://cloud.githubusercontent.com/assets/15335323/11391008/20fe0ec8-938a-11e5-8947-317ae2c91377.png)

Can you please give some suggestions ?
Thanks
Regards

**Comment by PercATI** [comment]
You need to run the realsense camera node separately. 
Did you do so?

Thanks,
Amit

**Comment by Wesley-Lin** [comment]
Hi Amit, 
Do you mean that I need to run "realsense_r200_launch.launch" and "roscore" separately ?
=> yes, I do
And I suspect that R200 doesn't be opened well, so it doesn't have data to publish topic.
Is there any wrong steps I enter ?

Thanks
Regards

**Comment by PercATI** [comment]
Send me the output of the command "roslaunch realsense realsense_r200_launch.launch"
You can run RVIZ to view the camera data as well.

Thx,
Amit

**Comment by Wesley-Lin** [comment]
Hi Amit,

The log is below,
... logging to /home/wesley/.ros/log/543b41ca-9353-11e5-81d4-b1114044eaba/roslaunch-wesley-desktop-21552.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wesley-desktop:50658/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    CImageViewerNodelet (nodelet/nodelet)
    standalone_nodelet_viewer (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[standalone_nodelet_viewer-1]: started with pid [21570]
process[CImageViewerNodelet-2]: started with pid [21571]

And rviz cannot show image neither
![rviz](https://cloud.githubusercontent.com/assets/15335323/11393535/1e6ab768-939b-11e5-823e-ea37571b592b.png)

Thanks,
Regards

**Comment by PercATI** [comment]
I do not see the output of this command:
"roslaunch realsense realsense_r200_launch.launch"

**Comment by Wesley-Lin** [comment]
Hi Amit,
sorry to copy wrong log to you, the log is below,

... logging to /home/wesley/.ros/log/dacb03aa-9363-11e5-8a2c-7756b8107fba/roslaunch-wesley-desktop-22776.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wesley-desktop:33833/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    CR200Nodelet (nodelet/nodelet)
    standalone_nodelet (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[standalone_nodelet-1]: started with pid [22794]
process[CR200Nodelet-2]: started with pid [22795]
[ INFO] [1448449355.525038330]: Initializing nodelet with 4 worker threads.
[ INFO] [1448449355.577090878]: Starting DS4 Camera node
[ INFO] [1448449355.769939908]: Setting directory to 0
[ INFO] [1448449355.769999137]: Setting recordToFile to 0
[ INFO] [1448449355.770017924]: Setting playFromFile to 0
[ INFO] [1448449355.770033988]: Setting enableColor to 1
[ INFO] [1448449355.770056185]: Setting enableDepth to 1
[ INFO] [1448449355.770074349]: Setting pcScale to 1000
[ INFO] [1448449355.770094752]: Setting cHeight to 480
[ INFO] [1448449355.770116495]: Setting cWidth to 640
[ INFO] [1448449355.770133143]: Setting dHeight to 360
[ INFO] [1448449355.770150110]: Setting dWidth to 480
[ INFO] [1448449356.097378530]: 1 cameras connected
[ INFO] [1448449356.259854097]: Firmware version: 1.0.71.01
[ INFO] [1448449356.259896350]: Software version: 1.16.14.0
[ INFO] [1448449356.259931546]: Camera serial no: 2131005330
[ INFO] [1448449356.260916238]: Allowed exposure range 0.1 to 16.4
[ INFO] [1448449356.261351009]: Allowed gain range 1 to 63.99

Regards

**Comment by PercATI** [comment]
It seems like the camera is working correctly.
Do you see something when you type rostopic echo /camera/depth/image_raw?

**Comment by Wesley-Lin** [comment]
Hi Amit,

There is nothing to show when I type "rostopic echo /camera/depth/image_raw
![echo_topic](https://cloud.githubusercontent.com/assets/15335323/11413413/7fc14fc6-9423-11e5-8831-10fc79c35e43.png)

Thanks
Regards

**Comment by Wesley-Lin** [comment]
Hi Amit,

Do you have any idea for the issue, I still cannot understand why it don't work 
Thanks

Regards

**Comment by PercATI** [comment]
Hi,

Might it be an OpenCV version issue (see here: https://github.com/ros-perception/image_pipeline/issues/136)

can you try running the rqt_image_view  ?

thanks,
Amit

**Comment by Wesley-Lin** [comment]
Hi Amit,

I run the rqt_image_view, however, the content in windows is still empty.
![rqt_image_view](https://cloud.githubusercontent.com/assets/15335323/11499257/b97f64f6-985f-11e5-86f7-b96479a914c2.png)

And I had installed the OpenCV 2.4.11 before, because I need it to do image processing. according your link, does it mean I need to uninstall it ? 

Thanks
Regards

**Comment by PercATI** [comment]
Hi,

I'm checking.
It might be this.

Thanks,
Amit

**Comment by mattcurfman** [comment]
This looks a lot like an issue I saw also, and found this discussion: https://github.com/ros-perception/image_pipeline/issues/136

I uninstalled my own OpenCV 2.4.11 then verified it working again.  I haven't yet had a chance to investigate the actual source of the incompatibility.

**Comment by Wesley-Lin** [comment]
Hi @mattcurfman and @PercATI   
I will uninstalled the OpenCV and try it again, then I would feedback the test result.

And for @mattcurfman 
Would you mind I ask you a question ?  Is there any chance to solve that r200 need to be physically unplug and re-plug ?  I had used the software reset, but it is not work every time.

Thanks your help
Regards

**Comment by mattcurfman** [comment]
It would be interesting to try the patch for kernel uvcvideo.ko listed at https://patchwork.linuxtv.org/patch/25668 (which is in the newer v4.0 kernels) and see if that helps with the software reset issue?
