### ISSUE TITLE
How to run it on any ARM-based platform?

### ISSUE THREAD

**Issue by gmhuili** [PercATI/RealSense_ROS#20]
Any plan to release all source?

**Comment by gmhuili** [comment]
Or intel tries not to run it on other families?

**Comment by gmhuili** [comment]
Will it work on intel compute stick Z3735F?

**Comment by PercATI** [comment]
Hi,

This is an experimental code. We will publish information regarding support in the future.
I don't have it at the moment. We tested it on Intel Core devices.

Thanks,
Amit
