### ISSUE TITLE
Camera Calibration (/camera/set_camera_info service) with ROS

### ISSUE THREAD

**Issue by mjedmonds** [PercATI/RealSense_ROS#22]
I've been trying to find a way to calibrate the RealSense camera using ROS. More specifically, I've been trying to use: http://wiki.ros.org/camera_calibration. The ROS camera calibration expects that there is a /camera/set_camera_info service.

I'd be more than happy to work to make this service if it does not exist (which it appears to not) or if there isn't another way to calibrate the camera.

**Comment by PercATI** [comment]
Hi,
Sorry about that. You are obviously right. I hope that in the near future we will be able to provide sources to the ROS wrappers.

**Comment by int3ll3ct** [comment]
for what it's worth, I successfully used the usb_cam package to calibrate my RealSense F200 RGB cam (ultimately generating a YAML file) using camera_calibration. However, I use a different ROS package to interface with the F200, so I cannot comment on getting RealSense_ROS to recognize/use/publish the calibration matrices.

**Comment by skohlbr** [comment]
As mentioned also on ROS Answers (http://answers.ros.org/question/223530/intel-realsense-r200-camera-calibration/), the check for the calibration service can be ignored via the "--no-service-check" command-line option.

**Comment by mjedmonds** [comment]
@skohlbr's suggestion worked!
