### ISSUE TITLE
DSAPI call failed....   ...Failed to grab the Z frame

### ISSUE THREAD

**Issue by thieri** [PercATI/RealSense_ROS#26]
Hello,
seems to be the same error, "niezeroxue" stumbled upon.

A few weeks ago, everything went fine, but today...
   ...Failed to grab the Z frame...

Launch-files are unchanged, but kernel and firmware could be new.

I was testing some code under windows, (where the r200 works like a charm), did the update to firmware 1.0.72.04.

running the Nodelet gives me...

process[R200/Depth2Laser/R200ScanLower-6]: started with pid [18509]
[ INFO] [1452541352.680553021]: Initializing nodelet with 4 worker threads.
[ INFO] [1452541352.817818422]: Starting DS4 Camera node
[ INFO] [1452541353.213932292]: Setting directory to 0
[ INFO] [1452541353.214008263]: Setting recordToFile to 0
[ INFO] [1452541353.214035797]: Setting playFromFile to 0
[ INFO] [1452541353.214064757]: Setting enableColor to 1
[ INFO] [1452541353.214095110]: Setting enableDepth to 1
[ INFO] [1452541353.214147304]: Setting cFPS to 30
[ INFO] [1452541353.214197165]: Setting dFPS to 30
[ INFO] [1452541353.214249523]: Setting pcScale to 1000
[ INFO] [1452541353.214311172]: Setting cHeight to 480
[ INFO] [1452541353.214363623]: Setting cWidth to 640
[ INFO] [1452541353.214418384]: Setting dHeight to 360
[ INFO] [1452541353.214470427]: Setting dWidth to 480
[ INFO] [1452541353.570723593]: 1 cameras connected
[ INFO] [1452541353.780540072]: Firmware version: 1.0.72.04
[ INFO] [1452541353.780659667]: Software version: 1.16.14.0
[ INFO] [1452541353.780761350]: Camera serial no: 2211004567
[ INFO] [1452541353.784522046]: Allowed exposure range 0.1 to 16.4
[ INFO] [1452541353.786123415]: Allowed gain range 1 to 63.99

trying to reinstall the patches (sudo su, ./install.sh) I get this error/warning from the installer

patching file drivers/media/usb/uvc/uvc_driver.c
Hunk #1 succeeded at 142 (offset 20 lines).
patching file drivers/media/usb/uvc/uvcvideo.h
Hunk #1 succeeded at 116 (offset 12 lines).
patching file include/uapi/linux/videodev2.h
Hunk #1 succeeded at 527 with fuzz 2 (offset 99 lines).
patching file drivers/media/usb/uvc/uvc_video.c
Hunk #1 FAILED at 1846.
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/uvc/uvc_video.c.rej

I am using linux-lts-vivid (linux-image-3.19.0-43-generic)

Is there a list of "working" kernels?

**Comment by thieri** [comment]
Worked all nicht... With kernel 3.13.0-47 the installter works, but i have to plug in cam after start/boot..

**Comment by PercATI** [comment]
Hi,

Make sure the /dswork.lock is deleted.
