### ISSUE TITLE
NEW OPEN SOURCE DRIVER

### ISSUE THREAD

**Issue by PercATI** [PercATI/RealSense_ROS#28]
Hi all,

Great news!  @ddiakopoulos just posted a new official open source driver for Intel RealSense cameras!
https://github.com/IntelRealSense/librealsense

ROS driver will be provided in the near future as well.

Thx,
Amit

**Comment by wqf233333** [comment]
Hi @PercATI   Amit, I found there are more than one  ROS driver for R200 , and I know your work for Intel. So which driver should I choose?  

And when I test your driver on Ubuntu 14.04.3 (x64)，If if use
1.roslaunch realsense realsense_r200_launch.launch
2.  rosrun image_view image_view image:=/camera/color/image_raw
Then I can get color image.
But when I use these command:
1.roslaunch turtlebot_bringup minimal.launch
2.roslaunch realsense realsense_r200_launch.launch 
 3.rosrun image_view image_view image:=/camera/color/image_raw
I can not get color image of R200.
So I can not run realsense_dist_nav.
What is the problem?

**Comment by PercATI** [comment]
hi,

can you run RVIZ and see any of the images? (depth/color/pc)?

**Comment by wqf233333** [comment]
hi,I can not get images in rviz. And  a friend suggest that is the problem of gcc 4.9 and uvc patch, I will try it again.    

Does  this  ros version  base on the official linux driver ?  I  tested the linux driver  in ubuntu, it works well.

**Comment by PercATI** [comment]
This version of ROS wrapper is using another driver (not the open source one).

**Comment by int3ll3ct** [comment]
So, ar eyou going to be hosting the "official open source RealSense ROS pacakge" at PercATI/RealSense_ROS, or is that expected to be eventually hosted and driven out of https://github.com/IntelRealSense/?

**Comment by PercATI** [comment]
I cannot say yet. We will update once ready.

**Comment by viktorku** [comment]
Hi Amit,

Do you have any idea when is the official RealSense ROS package going to be released? Is it a matter of few weeks from now or few months?

Thanks for the info.

**Comment by PercATI** [comment]
Hi,

Few weeks. We are finalizing it.

thx,
Amit

**Comment by PercATI** [comment]
Hi,

Please move to the new driver & ROS wrapper here: https://github.com/intel-ros/realsense
It should solve most of the issues and it is all open sourced :)

Thx,
Amit
