### ISSUE TITLE
open f200 device failed

### ISSUE THREAD

**Issue by peterlin300** [PercATI/RealSense_ROS#29]
hi！i met a problem when i try to run roslaunch realsense realsense_f200_launch.launch
i already have run ivcam_sample, everything seems ok! i see the dots apearing on the screen
After i run roslaunch realsense realsense_f200_launch.launch, it shows

started roslaunch server http://turtlebot:54885/

PARAMETERS
 * /rosdistro
 * /rosversion

NODES
  /
    CF200Nodelet (nodelet/nodelet)
    standalone_nodelet (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [18314]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c6202f10-c8f7-11e5-abe1-fcf8ae19ec63
process[rosout-1]: started with pid [18327]
started core service [/rosout]
process[standalone_nodelet-2]: started with pid [18339]
  [ INFO] [1454340221.576927923]: Initializing nodelet with 4 worker threads.
process[CF200Nodelet-3]: started with pid [18349]
### [ERROR] [1454340221.690010719]: Failed to load nodelet [/CF200Nodelet] of type [f200_ros/CF200Nodelet]: Failed to load library /opt/ros/hydro/lib//libf200_camera_nodelet.so.
 Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. 
### Error string: Could not load library (Poco exception = libboost_system.so.1.54.0: cannot open shared object file: No such file or directory)
[FATAL] [1454340221.690209230]: Service call failed!
[CF200Nodelet-3] process has died [pid 18349, exit code 255, cmd /opt/ros/hydro/lib/nodelet/nodelet load f200_ros/CF200Nodelet standalone_nodelet pcScale 1000 cHeight 480 cWidth 640 dHeight 480 dWidth 640 enableColor 1 enableDepth 1 __name:=CF200Nodelet __log:=/home/turtlebot/.ros/log/c6202f10-c8f7-11e5-abe1-fcf8ae19ec63/CF200Nodelet-3.log].
log file: /home/turtlebot/.ros/log/c6202f10-c8f7-11e5-abe1-fcf8ae19ec63/CF200Nodelet-3*.log

i am a beginner in ubuntu14.04 and ros(hydro)
could you help me how to solve this problem step by step?! thanks very much
best regard!!

**Comment by peterlin300** [comment]
sorry im post wrong ,i should post in F200

**Comment by PercATI** [comment]
Hi,

the original node was written for Indigo.

Also, we removed the F200 node and we will have a new one soon using the new driver.

thx,
Amit

**Comment by peterlin300** [comment]
thanks! i find it is for indigo this afternoon!
