### ISSUE TITLE
image_view problem

### ISSUE THREAD

**Issue by ashokaravinda** [PercATI/RealSense_ROS#30]
Hi,

I followed your instructions and installed the driver / rosnode. 

When I run,
roslaunch realsense realsense_r200_launch.launch
command, it gives me '1 camera connected' info line with few other details.

Then when I run, 
rosrun image_view image_view image:=/camera/color/image_raw,
I get below,
_(image_view:6829): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GtkWidget'

(image_view:6829): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(image_view:6829): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed_

Please note that I'm new to ROS. 
What can be the issue ?

**Comment by ashokaravinda** [comment]
Hi,
There was a problem with my openCV version and after sorting that out image_view problem was resolved. 
But I'm having another issue. I get "status:  DS_FIRMWARE_OUT_OF_DATE", after I run roslaunch command.

Any clue on this ?

**Comment by ashokaravinda** [comment]
I updated the firmware using Intel RealSense Depth Camera Manager in Windows and now the above message doesn't appear anymore. Furthermore, the image_view shows the image stream as well.
The problem is, after sometime (10-20 seconds), the image stream stops showing below error message continuously, 
[ERROR] [1454387626.543687955]: No R200 Camera connected.

When I remove and re-plug the camera, it works and stops again after few seconds.

**Comment by PercATI** [comment]
Hi,

Try to plug in the camera and quickly start the node. (want to see if this is the connectivity issue).

thx,
Amit

**Comment by ashokaravinda** [comment]
Hi Amit,

Thank you for you response.
I tried as you suggested, but I'm still getting the error. 

I checked other issues on the list, and I saw "Failed to grab the Z frame" error. Is this what you meant by connectivity issue ?
In my case it says "Failed to grab the Third frame". What this third frame might be ?
In some cases camera works for more than 30 seconds (sometimes 2,3 seconds) and then gives the error. So I believe third frame doesn't mean the third frame from the beginning of image stream.

**Comment by ashokaravinda** [comment]
Hi,

I installed new https://github.com/IntelRealSense/librealsense driver, and without changing anything else, the ros node seems consistent than previous case. 
I installed Video4Linux backend, with Stock 3.19.xx Kernel in 14.04.xx option.

In some occasions it doesn't give the error (I kept the ros node running more than 30 mins !), but in some cases it gives the error after sometime (few minutes). 
It seems far better than the previous case, but still the error comes time to time.

What would be the reason as you think ?

**Comment by PercATI** [comment]
Hi,

Do you experience similar problems on windows machine?
Can yo try to update the kernel?
check out this issue:
https://github.com/PercATI/RealSense_ROS/issues/23

**Comment by ashokaravinda** [comment]
Hi,

I updated my kernel using 
`sudo apt-get install linux-generic-lts-vivid` and then installed the drivers again (your driver and the librealsense by intel). 
still I get the same error : Failed to grab the Thrid frame.
Initially I saw the image stream and got this error and after few restarts, not I'm getting this error just after 5-6 seconds (no image stream in ROS image_view).

Do you think this is a problem with the camera hardware, or driver ?

BR

**Comment by ddiakopoulos** [comment]
What is the output of dmesg after streaming fails? Can you attach the output as a text file here?

Can you update to the Ubuntu 4.4 kernel as outlined in the librealsense readme and make sure you re-patch the driver? 

What is the version of your camera firmware? Check one of the librealsense examples to see how you can log that info.

**Comment by rFalque** [comment]
Hi,

I am facing the same problem. I updated to the 4.4 kernel and re-patch the drivers. It didn't solve the problem.

The output of dmesg is the following one:

> [  133.170360] nodelet[2872]: segfault at 0 ip 00007f4cec13010f sp 00007ffcbec56f40 error 4 in libr200_camera_nodelet.so[7f4cec11a000+2e000]


Any idea of what could go wrong?

**Comment by ashokaravinda** [comment]
Hi,

Yes, these are two different problems. I also updated to linux 4.4 and followed the guide. Still I'm getting the error. 

My dmesg shows below, after the error.
sysfs group ffffffff81ec5e80 not found for kobject 'input23'

I attached the dmesg txt file for your reference.

[dmesg.zip](https://github.com/PercATI/RealSense_ROS/files/122510/dmesg.zip)

BR

**Comment by ashokaravinda** [comment]
Hi,

I ran the provided examples (instead of roslaunch) such as cpp-capture and after a while it stops too. 
When I type dmesg on terminal it showed the below error,
uvcvideo: Failed to set UVC probe control : -32 (exp. 34).

Full dmesg is attached below. 

[dmesg.zip](https://github.com/PercATI/RealSense_ROS/files/122596/dmesg.zip)

**Comment by PercATI** [comment]
Hi,

Please move to the new driver & ROS wrapper here: https://github.com/intel-ros/realsense
It should solve most of the issues and it is all open sourced :)

Thx,
Amit
