### ISSUE TITLE
realsense navigation problem

### ISSUE THREAD

**Issue by niezeroxue** [PercATI/RealSense_ROS#31]
Hi Amit:
    I have bought a turtlebot to test the realsense navigation pkg, I placed the r200 and changed the parameter in the r200.urdf.xacro, but the navigation result was too bad(the turtlebot hit person, and made wrong way). Should I do some others jobs before running it?
    Then I found the camera_link frame was a little distance from the camera_rgb_frame, the picture is shown below, I was quite puzzled how we set the position of the camera_link?

![27975447266465557](https://cloud.githubusercontent.com/assets/6767575/12776598/3d844dca-ca92-11e5-95b2-98c0dcdc8e9e.jpg)

Thanks

**Comment by PercATI** [comment]
Hi, 
You should modify the URDF to match the configuration of your robot.
