### ISSUE TITLE
How to load Camera Calibration Yaml file

### ISSUE THREAD

**Issue by Nikvand** [PercATI/RealSense_ROS#32]
Hi All I have two questions which I will ask in the same post and hopefully that is not against the law. 

1- I can see that the nodelet is already publishing into /camera/color/camera_info the calibration information for this camera, I was wondering where is the data stored [as I couldn't find a Yaml file or any other similar info anywhere in the package] and how is it loaded into the nodelet and how can I use my own calibration data. 

2- With the existing /camera/color/camera_info topic, I tried to rectify the raw image by image_proc node and subscribing to /camera/color/image_rect_color topic as specified in the image_proc manual, however I am not getting any rectification and I am getting a message that the published topic is the same as image_raw. And if you are wondering, I did not forget to subscribe to /camera/color/image_rect_color in my application node.

I appreciate any help and comments.

**Comment by PercATI** [comment]
Hi,

1. the data i burned on the camera themselves at the factory.
2. I am not sure what is the reason but I will ask you to try our new supported version: https://github.com/intel-ros/realsense
This version is deprecated as we moved to a newer camera driver.

thanks,
Amit
