### ISSUE TITLE
Exposure control?

### ISSUE THREAD

**Issue by ruffsl** [PercATI/RealSense_ROS#5]
I'd like to know if its possible to control or fix the RGB exposure rate of the realsense programmatically?

**Comment by PercATI** [comment]
Hi,

No, this feature is not available.

Amit

**Comment by ruffsl** [comment]
Just curious if this is an implementable feature, or is a property that the device itself does not support?

**Comment by PercATI** [comment]
Not sure. we are working on different options for distribution so it will depend on it.
