### ISSUE TITLE
F200 support timeline?

### ISSUE THREAD

**Issue by int3ll3ct** [PercATI/RealSense_ROS#8]
Hi PercATI,

Forgive me for misusing the Issues function in Github to ask this, but what is the outlook for F200 support?

I have a ROS homebrew project that I was planning to use the F200 for, because of its near-field capability.  I am aware of teknotus' work on the F200, but I now I see that this project you're running has the appearance of being Intel-supported, so I assume this bodes well for the project.

I've dabbled in ROS this year, and I was a FW/driver programmer for years, so rather than just asking you "when", I'm inquiring if you're looking for people to throw in a few hours and brain cells here and there to help things move forward.  Let me know...

**Comment by PercATI** [comment]
Hi,

We have a solution but need to fix some dependencies problem. We will have something soon. 

Thank you very much for the proposition. It is very interesting but we need to clarify some IP things internally before we can open source the solution.

Please stay tuned. It might be possible in the near future.

Thanks,
Amit

**Comment by floe** [comment]
I'll second this. I am one of the maintainers of libfreenect2, so I know my way around depth cameras - if any help is needed, I'd be glad to chip in. Hopefully the IP issues are solved soon.
