### ISSUE TITLE
R200 nodelet runtime error

### ISSUE THREAD

**Issue by robotsoft** [PercATI/RealSense_ROS#9]
Hi,

When I run "realsense_r200_launch.launch", I've encountered the error follows.

[ INFO] [1446502798.207895094]: 1 cameras connected
[ INFO] [1446502798.569964630]: Firmware version: 1.0.71.01
[ INFO] [1446502798.570111558]: Software version: 1.16.14.0
[ INFO] [1446502798.570207101]: Camera serial no: 2211008053
[ INFO] [1446502798.570839417]: Allowed exposure range 0.1 to 16.4
[ INFO] [1446502798.571108272]: Allowed gain range 1 to 63.99
[ERROR] [1446502801.814122530]: 
DSAPI call failed at /home/turtlebot/catkin_ws/src/realsense_ros/src/r200_camera_nodelet.cpp:509!
  status:  DS_FAILURE
  details: Internal exception: Failed to grab the Z frame

 hit return to exit 

Any comment would be appreciated.

I ran it on Ubuntu 14.04 LTS with ROS indigo.

Thank you,

**Comment by PercATI** [comment]
Hi,

Did the driver was well installed?
Are you connected to USB3?

thanks,
Amit

**Comment by robotsoft** [comment]
I solved this issue by installing the driver again. Thank you for comments.

**Comment by PercATI** [comment]
OK. Great!

Thanks for letting us know.
Amit
